



tuto_test_filter:
    path:     /filter/
    defaults: { _controller: TutoTestBundle:Default:filters }

tuto_test_resultat:
    path:     /resultat/
    defaults: { _controller: TutoTestBundle:Default:resultat }


